name = "rps"
main = "src/worker.js"
compatibility_date = "2025-01-01"

[assets]
directory = "./public"
binding = "ASSETS"

[[durable_objects.bindings]]
name = "LOBBY"
class_name = "Lobby"

[[durable_objects.bindings]]
name = "RATING"
class_name = "Rating"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["Lobby"]

[[migrations]]
tag = "v2"
new_sqlite_classes = ["Rating"]
